export { default as LoginPage } from './login'
export { default as RegisterPage } from './register'
export { default as HomePage } from './home'
export { default as PostPage } from './posts/[id]'
export { default as ProfileIndexPage } from './profile/[id]'
export { default as ProfileFollowingPage } from './profile/[id]/following'